# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsmgr < Formula
  desc "Operational workflow and environment diagnostics tool for AWS engineers."
  homepage "https://github.com/santhosh-john/awsmgr"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/santhosh-john/awsmgr/releases/download/v1.0.1/awsmgr_1.0.1_darwin_amd64.tar.gz"
      sha256 "9f1499396ea0053b0980f8869b10fddf67e86c3646f6b7efe5aefceb04cc0523"

      define_method(:install) do
        bin.install "awsmgr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/santhosh-john/awsmgr/releases/download/v1.0.1/awsmgr_1.0.1_darwin_arm64.tar.gz"
      sha256 "9d8d40730ce74e44af3d459a336e148136bc3dbaf70b2fd1acaaf0621d46742c"

      define_method(:install) do
        bin.install "awsmgr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/santhosh-john/awsmgr/releases/download/v1.0.1/awsmgr_1.0.1_linux_amd64.tar.gz"
      sha256 "6453ed4803d9f2853e560d67e58ff166e6dcd60a9aa4f81e2811e7729a2b8a55"
      define_method(:install) do
        bin.install "awsmgr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/santhosh-john/awsmgr/releases/download/v1.0.1/awsmgr_1.0.1_linux_arm64.tar.gz"
      sha256 "014133d18e43df1bd5f9e01f1c05f4b8de425edf7cc28bccd623fe228101e576"
      define_method(:install) do
        bin.install "awsmgr"
      end
    end
  end
end
