# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsmgr < Formula
  desc "Operational workflow and environment diagnostics tool for AWS engineers."
  homepage "https://github.com/santhosh-john/awsmgr"
  version "1.0.1-beta-03"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/santhosh-john/awsmgr/releases/download/v1.0.1-beta-03/awsmgr_1.0.1-beta-03_darwin_amd64.tar.gz"
      sha256 "40c083a2d98073f3d466552dcd83a4479a87cafa16805e45beae43df8b2078df"

      define_method(:install) do
        bin.install "awsmgr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/santhosh-john/awsmgr/releases/download/v1.0.1-beta-03/awsmgr_1.0.1-beta-03_darwin_arm64.tar.gz"
      sha256 "4721f788adb7d43c51597ff02e0a36bcd4e7d5109161d00533f01311c66e957f"

      define_method(:install) do
        bin.install "awsmgr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/santhosh-john/awsmgr/releases/download/v1.0.1-beta-03/awsmgr_1.0.1-beta-03_linux_amd64.tar.gz"
      sha256 "368c7b32a6980f5204719e246b7d386145e1c16a9f382fc7d4bde4931a3d6db2"
      define_method(:install) do
        bin.install "awsmgr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/santhosh-john/awsmgr/releases/download/v1.0.1-beta-03/awsmgr_1.0.1-beta-03_linux_arm64.tar.gz"
      sha256 "0bd5abcd74a0b24a8cfd15a225b9cde195023533d58881ecf01bbeb3408c8665"
      define_method(:install) do
        bin.install "awsmgr"
      end
    end
  end

  test do
    system "#{bin}/awsmgr", "help"
  end
end
