# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsmgr < Formula
  desc "Operational workflow and environment diagnostics tool for AWS engineers."
  homepage "https://github.com/santhosh-john/awsmgr"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/santhosh-john/awsmgr/releases/download/v1.1.0/awsmgr_Darwin_x86_64.tar.gz"
      sha256 "d351f761f803bdb8389ddfdef816019a06299bd6ed6f50aa0d6c0a74d2a55582"

      define_method(:install) do
        bin.install "awsmgr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/santhosh-john/awsmgr/releases/download/v1.1.0/awsmgr_Darwin_arm64.tar.gz"
      sha256 "290b3165676bd97c316d4a0e611ff36e97cf06977ec03227c41b7f74cb154467"

      define_method(:install) do
        bin.install "awsmgr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/santhosh-john/awsmgr/releases/download/v1.1.0/awsmgr_Linux_x86_64.tar.gz"
      sha256 "f6d4eade3ebbd7a9723a964454cc18bb12a1cab584978797065754e3b2e1614e"
      define_method(:install) do
        bin.install "awsmgr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/santhosh-john/awsmgr/releases/download/v1.1.0/awsmgr_Linux_arm64.tar.gz"
      sha256 "99618da224d49bf68d8af3d1e64d538c7a06f459b44452ea6492021be6535447"
      define_method(:install) do
        bin.install "awsmgr"
      end
    end
  end

  test do
    system "#{bin}/awsmgr", "version"
  end
end
