# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsmgr < Formula
  desc "Operational workflow and environment diagnostics tool for AWS engineers."
  homepage "https://github.com/santhosh-john/awsmgr"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/santhosh-john/awsmgr/releases/download/v1.0.0/awsmgr_1.0.0_darwin_amd64.tar.gz"
      sha256 "feb1e656db33862553487022970d7195f55d9ed5c14113c7a86d2190857ca1a3"

      define_method(:install) do
        bin.install "awsmgr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/santhosh-john/awsmgr/releases/download/v1.0.0/awsmgr_1.0.0_darwin_arm64.tar.gz"
      sha256 "14822c87af97b0636ca00bbe3ef9ec57121c84bc5a8c4aeaf45bb2141d60b423"

      define_method(:install) do
        bin.install "awsmgr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/santhosh-john/awsmgr/releases/download/v1.0.0/awsmgr_1.0.0_linux_amd64.tar.gz"
      sha256 "22574cf915d7cec91e45e6e3b5a302db1fd176657f2ee85a380a570d19eb4736"
      define_method(:install) do
        bin.install "awsmgr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/santhosh-john/awsmgr/releases/download/v1.0.0/awsmgr_1.0.0_linux_arm64.tar.gz"
      sha256 "1f44da7be93bc68f8d4ee0e6be1e158499c96e44ab8343150d9b627fa730763e"
      define_method(:install) do
        bin.install "awsmgr"
      end
    end
  end

  test do
    system "#{bin}/awsmgr", "help"
  end
end
